openapi: 3.0.3
info:
  title: Date Choice Bot API
  version: 1.0.0
  description: API for a bot that allows users to choose dates and view all selections.

servers:
  - url: /api

paths:
  /date/choice:
    post:
      summary: User selects dates
      description: User submits their chosen dates.
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
          description: Telegram initData for authentication (tma)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - dates
              properties:
                dates:
                  type: array
                  description: List of selected dates (YYYY-MM-DD)
                  items:
                    type: string
                    format: date
      responses:
        '200':
          description: Dates successfully saved
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
        '400':
          description: Invalid request (e.g., missing or malformed dates)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid dates format
        '401':
          description: Unauthorized (invalid or missing tma-init-data)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized

  /date/choiced:
    get:
      summary: Get user's date choices
      description: Returns the dates selected by the user.
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
          description: Telegram initData for authentication (tma)
      responses:
        '200':
          description: User's selected dates
          content:
            application/json:
              schema:
                type: object
                properties:
                  dates:
                    type: array
                    items:
                      type: string
                      format: date
                example:
                  dates: ["2024-06-01", "2024-06-05"]
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Bad request
        '401':
          description: Unauthorized (invalid or missing tma-init-data)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized

  /date/all:
    get:
      summary: Get all date choices
      description: Returns all users and their selected dates.
      responses:
        '200':
          description: List of users and their chosen dates
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    user_id:
                      type: integer
                      description: Unique user identifier
                      example: 2348956345
                    user_name:
                      type: string
                      description: Username of the user
                      example: testTestLinux
                    dates:
                      type: array
                      items:
                        type: string
                        format: date
                      description: List of selected dates (YYYY-MM-DD)
                  required:
                    - user_id
                    - user_name
                    - dates
              example:
                - user_id: 34534563465
                  user_name: testTestLinux
                  dates: ["0001-01-01"]
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Bad request
        '401':
          description: Unauthorized (invalid or missing tma-init-data)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized

  /date/interval:
    get:
      summary: Get date selection interval
      description: Returns the start and end dates for the selection interval.
      responses:
        '200':
          description: Date selection interval
          content:
            application/json:
              schema:
                type: object
                properties:
                  start_date:
                    type: string
                    format: date
                    description: Start date of the interval (YYYY-MM-DD)
                    example: "2024-01-01"
                  end_date:
                    type: string
                    format: date
                    description: End date of the interval (YYYY-MM-DD)
                    example: "2024-12-31"
                required:
                  - start_date
                  - end_date
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Bad request
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized